# Note:  This is an example config, see habitat_baselines/config/pointnav/ppo_pointnav.yaml
# for better hyperparameters for actual training

BASE_TASK_CONFIG_PATH: "configs/tasks/object_rearrangement.yaml"
TRAINER_NAME: "rearrangement-bc-env"
ENV_NAME: RearrangementRLEnv
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: ["disk"]
TENSORBOARD_DIR: "tb/resnet18_fold_0"
VIDEO_DIR: "video_dir/resnet18_fold_0"
# To evaluate on all episodes, set this to -1
TEST_EPISODE_COUNT: -1
EVAL_CKPT_PATH_DIR: "data/new_checkpoints/resnet18_fold_0/model_20.ckpt"
SHOW_TOP_DOWN_MAP: False
NUM_PROCESSES: 1
CHECKPOINT_FOLDER: "data/new_checkpoints/resnet18_fold_0"
OUTPUT_LOG_DIR: data/object_rearrangement/logs
LOG_INTERVAL: 10
LOG_METRICS: True
CHECKPOINT_INTERVAL: 1
DATASET_PATH: "data/datasets/object_rearrangement/v0/{split}/{split}.db"
RESULTS_DIR: "data/object_rearrangement/results/{split}/{type}"
EVAL_SAVE_RESULTS: True
EVAL_SAVE_RESULTS_INTERVAL: 50
EVAL:
  SPLIT: "eval"

IL:
  USE_IW: True
  distrib_training: False
  distrib_backend: GLOO

  BehaviorCloning:
    clip_param: 0.1
    num_mini_batch: 1
    lr: 1.0e-2
    eps: 1.0e-5
    max_grad_norm: 0.5
    num_steps: 8
    hidden_size: 512
    freeze_encoder: False
    reward_window_size: 50
    use_linear_lr_decay: True
    use_linear_clip_decay: True
  
  POLICY:
    name: "RearrangementSeqNetPolicy"

RL:
  REWARD_MEASURE: "agent_receptacle_distance"
  REWARD_MEASURE_2: "agent_object_distance"
  SUCCESS_MEASURE: "success"
  SLACK_REWARD: -0.01
  SUCCESS_REWARD: 2.5
  GRAB_SUCCESS_REWARD: 1.5

MODEL:
  inflection_weight_coef: 6.6991838665799275
  ablate_depth: False
  ablate_rgb: False
  ablate_instruction: False
  INSTRUCTION_ENCODER:
    vocab_size: 66
    embedding_size: 64
    hidden_size: 128
    use_pretrained_embeddings: False
    rnn_type: "LSTM"
    final_state_only: True
    bidirectional: False
  RGB_ENCODER:
    cnn_type: "ResnetRGBEncoder"
    output_size: 256
    backbone: "resnet18"
    train_encoder: True
  DEPTH_ENCODER:
    cnn_type: "VlnResnetDepthEncoder"
    output_size: 128
    backbone: "resnet50"
    ddppo_checkpoint: "data/ddppo-models/gibson-2plus-resnet50.pth"
    trainable: False
  STATE_ENCODER:
    hidden_size: 512
    rnn_type: "GRU"
    num_recurrent_layers: 2
  SEQ2SEQ:
    use_prev_action: True
  PROGRESS_MONITOR:
    use: False