# Note:  This is an example config, see habitat_baselines/config/pointnav/ppo_pointnav.yaml
# for better hyperparameters for actual training

BASE_TASK_CONFIG_PATH: "configs/tasks/object_rearrangement.yaml"
TRAINER_NAME: "rearrangement-behavior-cloning"
ENV_NAME: RearrangementRLEnv
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: ["disk", "tensorboard"]
TENSORBOARD_DIR: "tb"
VIDEO_DIR: "video_dir"
# To evaluate on all episodes, set this to -1
TEST_EPISODE_COUNT: 2
EVAL_CKPT_PATH_DIR: "data/new_checkpoints"
NUM_PROCESSES: 1
CHECKPOINT_FOLDER: "data/new_checkpoints"
NUM_UPDATES: 10000
LOG_INTERVAL: 50
CHECKPOINT_INTERVAL: 50
DATASET_PATH: "data/datasets/object_rearrangement/v0/{split}/{split}.db"

IL:
  BehaviorCloning:
    lr: 0.001
    max_epochs: 10
    batch_size: 4

RL:
  REWARD_MEASURE: "object_to_goal_distance"
  SUCCESS_MEASURE: "spl"
  SLACK_REWARD: -0.01
  SUCCESS_REWARD: 1.0
