# Note:  This is an example config, see habitat_baselines/config/pointnav/ppo_pointnav.yaml
# for better hyperparameters for actual training

BASE_TASK_CONFIG_PATH: "configs/tasks/object_rearrangement.yaml"
TRAINER_NAME: "rearrangement-behavior-cloning"
ENV_NAME: RearrangementRLEnv
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: ["disk"]
TENSORBOARD_DIR: "tb"
VIDEO_DIR: "video_dir"
# To evaluate on all episodes, set this to -1
TEST_EPISODE_COUNT: 10
EVAL_CKPT_PATH_DIR: "data/new_checkpoints/one_cycle_0_0001_epoch_700_sz_256_task_8_iw_10_4.ckpt"
NUM_PROCESSES: 1
CHECKPOINT_FOLDER: "data/new_checkpoints"
OUTPUT_LOG_DIR: data/object_rearrangement/logs
LOG_INTERVAL: 10
LOG_METRICS: True
CHECKPOINT_INTERVAL: 10
DATASET_PATH: "data/datasets/object_rearrangement/v0/{split}/{split}.db"
RESULTS_DIR: "data/object_rearrangement/results/{split}/{type}"
EVAL_SAVE_RESULTS: True
EVAL_SAVE_RESULTS_INTERVAL: 50
EVAL:
  SPLIT: "train"

IL:
  USE_IW: True
  BehaviorCloning:
    lr: 0.0005
    max_epochs: 500
    batch_size: 2
    freeze_encoder: False

RL:
  REWARD_MEASURE: "object_to_receptacle_distance"
  SUCCESS_MEASURE: "rearrangement_success"
  SLACK_REWARD: -0.01
  SUCCESS_REWARD: 1.0

MODEL:
  inflection_weight_coef: 8.966521106259098
  ablate_depth: False
  ablate_rgb: False
  ablate_instruction: False
  INSTRUCTION_ENCODER:
    vocab_size: 28
    max_length: 7
    embedding_size: 64
    hidden_size: 128
    use_pretrained_embeddings: False
    rnn_type: "LSTM"
    final_state_only: True
    bidirectional: False
  RGB_ENCODER:
    cnn_type: "TorchVisionResNet50"
    output_size: 256
  DEPTH_ENCODER:
    cnn_type: "VlnResnetDepthEncoder"
    output_size: 128
    backbone: "resnet50"
    ddppo_checkpoint: "data/ddppo-models/gibson-2plus-resnet50.pth"
  STATE_ENCODER:
    hidden_size: 512
    rnn_type: "GRU"
  SEQ2SEQ:
    use_prev_action: True
  PROGRESS_MONITOR:
    use: False