ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

SIMULATOR:
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ["RGB_SENSOR", "SEMANTIC_SENSOR", "DEPTH_SENSOR"]
  CROSSHAIR_POS: [256, 256]
  GRAB_DISTANCE: 2.0
  VISUAL_SENSOR: "rgb"
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ENABLE_PHYSICS: False
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 90
    TYPE: HabitatSimRGBSensor
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    POSITION: [0, 0.88, 0]
  SEMANTIC_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    POSITION: [0, 0.88, 0]
    CHANNELS: 1
TASK:
  TYPE: ObjectNav-v1
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN"]
  SUCCESS_DISTANCE: 0.1

  SENSORS: ['OBJECTGOAL_SENSOR', 'COMPASS_SENSOR', 'GPS_SENSOR']
  GOAL_SENSOR_UUID: objectgoal

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL']

  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS
  SUCCESS:
    SUCCESS_DISTANCE: 0.1

DATASET:
  TYPE: ObjectNav-v2
  SPLIT: train
  DATA_PATH: "data/datasets/objectnav_mp3d_v2/{split}/{split}.json.gz"
  SCENES_DIR: "data/scene_datasets/"
