ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  ACTION_SPACE_CONFIG: RearrangementActions-V0
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 15
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 90
    TYPE: HabitatSimRGBSensor
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: RearrangementTask-v0
  SUCCESS_DISTANCE: 3.0
  SENSORS: ['INSTRUCTION_SENSOR']
  INSTRUCTION_SENSOR_UUID: instruction
  POSSIBLE_ACTIONS: ['STOP', 'MOVE_FORWARD', 'MOVE_BACKWARD', 'TURN_LEFT', 'TURN_RIGHT', 'LOOK_UP', 'LOOK_DOWN', 'GRAB_RELEASE_OBJECT']
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCESS', 'SPL']
  SUCESS:
    SUCCESS_DISTANCE: 3.0
DATASET:
  TYPE: RearrangementDataset-v0
  SPLIT: train
  DATA_PATH: "data/datasets/lor/mp3d/v0/{split}/{split}.json.gz"
  SCENES_DIR: "data/scene_datasets/"
